const SET_PROFILE = "SET_PROFILE"
const UPDATE_PROFILE = "UPDATE_PROFILE"

const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER"
const SET_LOGOUT = "SET_LOGOUT"



export {
    SET_PROFILE,
    SET_LOGGED_IN_USER,
    SET_LOGOUT,
    UPDATE_PROFILE
}